onepagr_websites:
    pattern:  /sites/{name}
    defaults: { _controller: OnepagrTemplateBundle:Default:index, name: null }
onepagr_template_timeline:
    pattern:  /timeline/{name}
    defaults: { _controller: OnepagrTemplateBundle:Default:timeline }
onepagr_template_create:
    pattern:  /create/{name}
    defaults: { _controller: OnepagrTemplateBundle:Default:create }
onepagr_template_header:
    pattern:  /header/{name}
    defaults: { _controller: OnepagrTemplateBundle:Default:header }
onepagr_template_template:
    pattern:  /{folder}/{name}
    defaults: { _controller: OnepagrTemplateBundle:Default:template }
onepagr_template_page:
    pattern:  /page/{page}/{palette}
    defaults: { _controller: OnepagrTemplateBundle:Default:page }