parameters:
#    onepagr_template.example.class: Onepagr\TemplateBundle\Example

services:
#    onepagr_template.example:
#        class: %onepagr_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
