parameters:
#    ideallio_user.example.class: Ideallio\UserBundle\Example

services:
#    ideallio_user.example:
#        class: %ideallio_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
