security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Onepagr\UserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    access_decision_manager:
        strategy: unanimous

    providers:
        doctrine:
            id: nedwave_user.user_provider
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #           admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous:  ~
            context: application
            form_login:
                login_path:  onepagr_login
                check_path:  onepagr_login_check

            logout:
                path:   onepagr_logout
                target: /login

    access_control:
        - { path: ^/%locale%/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/password/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/password/request, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/password/change, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/content, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/%locale%/, role: IS_AUTHENTICATED_FULLY }
