parameters:
#    onepagr_user.example.class: Onepagr\UserBundle\Example

services:
#    onepagr_user.example:
#        class: %onepagr_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
